In [30]:
import matplotlib.pylab as plt
import numpy as np
%matplotlib inline
import statsmodels.api as sm
import os
import pandas as pd

C:\Users\user\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [4]:
os.getcwd()
os.chdir('C:\\Users\\user\\Desktop')

In [13]:
train = pd.read_csv("movie_data.csv",encoding = 'euc-kr')
test = pd.read_csv("test_data.csv", encoding = 'euc-kr')
train

,title,first_week_audience,first_day_screen,drama,action,comedy,fantasy.SF,advanture,criminal.thrill,traditional,...,etc,series,holiday,actors,director,distributor_value,aud_18,korea,usa,first_day_aud
0,"무현,두도시이야기",25506,87,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,6374
1,마담프루스트의비밀정원,25749,74,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,5934
2,유스,29946,129,1,0,0,0,0,0,0,...,0,0,0,6,0,0,0,1,0,8727
3,태풍이지나가고,32011,111,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,5995
4,파리로가는길,34437,158,1,0,0,0,0,0,0,...,0,0,0,4,0,0,0,0,1,9329
5,러브라이브!더스쿨아이돌무비,34582,123,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,16700
6,지금은맞고그때는틀리다,34897,109,1,0,0,0,0,0,0,...,0,0,1,11,0,2,1,1,0,10455
7,바다탐험대옥토넛시즌4바다괴물대소동,35587,247,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,1,0,4449
8,꼬마참새리차드아프리카원정대,36044,335,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,5638
9,리틀메딕몸속탐험대,36223,283,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,3274
10,본투비블루,36454,271,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,13329
11,러덜리스,36915,229,1,0,1,0,0,0,0,...,0,0,0,2,0,0,0,0,1,12198
12,바다탐험대옥토넛시즌4아슬아슬구조대작전,37171,198,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,2726
13,너와100번째사랑,40360,233,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,12607
14,더라스트나루토더무비,40638,231,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,16010
15,위아영,40971,469,1,0,1,0,0,0,0,...,0,0,0,6,0,0,0,0,1,13654
16,바다탐험대옥토넛시즌4늪지탐험선K,41210,178,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,2497
17,고녀석맛나겠다2함께라서행복해,41225,257,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,11457
18,아더와미니모이3두세계의전쟁,42129,221,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,2019
19,바다탐험대옥토넛스페셜,42328,301,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,6891
20,백설공주사라진아빠를찾아서,42669,239,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,2669
21,오두막,42962,778,1,0,0,0,0,0,0,...,0,0,0,4,0,0,0,1,0,13209
22,최악의하루,43452,395,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,14707
23,극장판파워레인저닌자포스VS트레인포스닌자인원더랜드,44186,455,0,1,0,0,0,0,0,...,0,0,0,0,0,2,0,1,0,4600
24,트럼보,44604,591,1,0,0,0,0,0,0,...,0,0,0,6,0,0,0,0,1,17920
25,포레스트죽음의숲,45763,569,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,10107
26,바다탐험대옥토넛시즌4더파이널,45836,192,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,2842
27,아메리칸셰프,45862,179,0,0,1,0,0,0,0,...,0,0,0,12,0,0,0,0,1,9097
28,이웃집에신이산다,46501,120,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,14944
29,대니콜린스,47398,598,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,17576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536,덕혜옹주,2209008,1545,1,0,0,0,0,0,1,...,0,0,0,16,1,3,0,1,0,536089
537,쥬라기월드,2230919,2126,0,1,0,0,1,0,0,...,0,0,0,2,0,1,0,1,0,587590
538,신비한동물사전,2238617,2351,0,0,0,0,1,0,0,...,0,0,0,2,0,2,0,1,0,519347
539,내부자들,2263674,1861,1,0,0,0,0,1,0,...,0,0,0,14,2,3,1,0,1,628251
540,해적바다로간산적,2329907,1581,0,0,0,0,1,0,0,...,0,0,0,7,1,3,0,0,1,563642
541,아가씨,2367281,2085,1,0,0,0,0,1,0,...,0,0,0,20,2,3,1,0,0,560763
542,역린,2461508,1942,0,0,0,0,0,0,1,...,0,0,0,11,0,3,0,0,1,653407
543,미이라,2490408,2383,0,1,0,0,1,0,0,...,0,0,0,7,0,1,0,0,1,1088233
544,밀정,2677678,2467,0,1,0,0,0,0,0,...,0,0,0,17,3,2,0,1,0,566403
545,럭키,2685607,1845,0,0,1,0,0,0,0,...,0,0,0,13,1,3,0,0,1,675721
546,인터스텔라,2687135,2228,0,0,0,1,0,0,0,...,0,0,0,8,0,2,0,0,1,572897
547,닥터스트레인지,2711347,2993,0,1,0,0,1,0,0,...,0,0,0,9,0,0,0,1,0,782065
548,청년경찰,2735797,2167,0,1,0,0,0,0,0,...,0,0,0,6,0,3,0,0,0,622378
549,트랜스포머사라진시대,2966999,3055,0,1,0,1,0,0,0,...,0,1,0,3,0,3,0,0,1,786762
550,곡성,3024092,2377,0,0,0,0,0,1,0,...,0,0,0,21,2,2,0,1,0,896217
551,마스터,3525592,2889,0,1,0,0,0,1,0,...,0,0,0,39,0,3,0,1,0,763624
552,터널,3533426,1674,1,0,0,0,0,0,0,...,0,0,0,25,1,3,0,0,1,760172
553,미션임파서블로그네이션,3563337,2373,0,1,0,0,0,1,0,...,0,1,0,10,0,3,0,0,1,971976
554,인천상륙작전,3584426,1805,1,0,0,0,0,0,0,...,0,0,0,23,1,3,0,0,0,831671
555,베테랑,3590029,1899,1,1,0,0,0,0,0,...,0,0,0,34,4,3,0,0,1,844547
556,군도민란의시대,3643920,2523,0,1,0,0,0,0,1,...,0,0,0,13,1,3,0,0,0,984932
557,스파이더맨홈커밍,4086159,3436,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,957304
558,암살,4195807,2594,1,1,0,0,0,0,0,...,0,0,0,18,3,3,0,0,1,926955
559,어벤져스에이지오브울트론,4319489,3498,0,1,0,0,1,0,0,...,0,1,0,42,0,0,0,1,0,1275470
560,캡틴아메리카시빌워,4446713,3673,0,1,0,1,0,0,0,...,0,1,0,17,0,0,0,1,0,1203236
561,군함도,4937342,3988,1,1,0,0,0,0,0,...,0,0,0,25,5,3,0,1,0,1552150
562,택시운전사,5407925,2999,1,0,0,0,0,0,0,...,0,0,0,25,3,3,0,0,0,1436582
563,검사외전,5469383,2686,0,0,1,0,0,1,0,...,0,0,1,24,0,3,0,0,0,1006364
564,부산행,6236450,3184,0,1,0,0,0,1,0,...,0,0,0,10,0,2,0,1,0,2101324
565,명량,6626792,2361,0,1,0,0,0,0,1,...,0,0,0,20,2,3,0,0,1,1410271

In [47]:
y_train = train.iloc[:,1]
x_train = train.iloc[:,2:]
y_test = test.iloc[:,1]
x_test = test.iloc[:,2:]

In [33]:
#sm.OLS(frist_week_audience, first_day_screen+drama+action, data = train)
model = sm.OLS(y_train, x_train)
result = model.fit()
print(result.summary())
#Durbin-Watson : 오차항끼리의 상관관계를 나타낸다. 2에 가까울 수록 상관관계가 없다.

                             OLS Regression Results
===============================================================================
Dep. Variable:     first_week_audience   R-squared:                       0.954
Model:                             OLS   Adj. R-squared:                  0.952
Method:                  Least Squares   F-statistic:                     469.6
Date:                 Thu, 22 Feb 2018   Prob (F-statistic):               0.00
Time:                         13:35:50   Log-Likelihood:                -7798.8
No. Observations:                  566   AIC:                         1.565e+04
Df Residuals:                      542   BIC:                         1.575e+04
Df Model:                           24
Covariance Type:             nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
first_day_screen    177.9472     31.572      5.636      0.000     115.928     239.966
drama             -4.768e+04   2.62e+04     -1.820      0.069   -9.91e+04    3768.717
action            -5.963e+04   2.77e+04     -2.150      0.032   -1.14e+05   -5144.472
comedy              758.4701    3.2e+04      0.024      0.981    -6.2e+04    6.36e+04
fantasy.SF        -5.732e+04   3.47e+04     -1.651      0.099   -1.26e+05    1.09e+04
advanture         -4.036e+04   3.13e+04     -1.289      0.198   -1.02e+05    2.11e+04
criminal.thrill   -5.151e+04   2.88e+04     -1.789      0.074   -1.08e+05    5037.165
traditional       -2.226e+04   6.55e+04     -0.340      0.734   -1.51e+05    1.06e+05
romance           -8.269e+04   3.82e+04     -2.167      0.031   -1.58e+05   -7737.152
animation          -1.65e+04   3.07e+04     -0.537      0.591   -7.68e+04    4.38e+04
documentary       -3.499e+04   8.64e+04     -0.405      0.685   -2.05e+05    1.35e+05
horror            -3.668e+04   5.01e+04     -0.732      0.464   -1.35e+05    6.17e+04
family            -1.075e+04   6.16e+04     -0.174      0.862   -1.32e+05     1.1e+05
war                 1.29e+04    1.1e+05      0.117      0.907   -2.03e+05    2.29e+05
etc               -1862.4575   1.21e+05     -0.015      0.988   -2.39e+05    2.35e+05
series             2.426e+04   2.94e+04      0.826      0.409   -3.34e+04    8.19e+04
holiday            1.485e+05    4.4e+04      3.374      0.001     6.2e+04    2.35e+05
actors             3478.0016   2227.135      1.562      0.119    -896.872    7852.876
director           2.105e+04   1.26e+04      1.676      0.094   -3615.206    4.57e+04
distributor_value   396.7047   8942.423      0.044      0.965   -1.72e+04     1.8e+04
aud_18            -4.692e+04   3.03e+04     -1.546      0.123   -1.07e+05    1.27e+04
korea             -4.216e+04   2.76e+04     -1.529      0.127   -9.63e+04     1.2e+04
usa                -2.16e+04   2.59e+04     -0.836      0.404   -7.24e+04    2.92e+04
first_day_aud         3.1535      0.079     39.949      0.000       2.998       3.309
==============================================================================
Omnibus:                      169.316   Durbin-Watson:                   1.959
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5032.779
Skew:                           0.648   Prob(JB):                         0.00
Kurtosis:                      17.551   Cond. No.                     3.50e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.5e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [38]:
new = result.predict(x_test)
new

0    1.119232e+06
1    1.309090e+06
2   -3.184414e+03
3   -3.421377e+04
4    1.287480e+05
dtype: float64

In [44]:
new_x_train = x_train.iloc[:, [0, 2, 8, 16, 23]]
new_x_test = x_test.iloc[:, [0, 2, 8, 16, 23]]
new_x_train

     first_day_screen  action  romance  holiday  first_day_aud
0                  87       0        0        0           6374
1                  74       0        0        0           5934
2                 129       0        0        0           8727
3                 111       0        0        0           5995
4                 158       0        1        0           9329
5                 123       0        0        0          16700
6                 109       0        0        1          10455
7                 247       0        0        1           4449
8                 335       0        0        0           5638
9                 283       0        0        0           3274
10                271       0        0        0          13329
11                229       0        0        0          12198
12                198       0        0        0           2726
13                233       0        1        0          12607
14                231       0        0        0          16010
15                469       0        0        0          13654
16                178       0        0        0           2497
17                257       0        0        0          11457
18                221       0        0        0           2019
19                301       0        0        0           6891
20                239       0        0        0           2669
21                778       0        0        0          13209
22                395       0        1        0          14707
23                455       1        0        0           4600
24                591       0        0        0          17920
25                569       0        0        0          10107
26                192       0        0        0           2842
27                179       0        0        0           9097
28                120       0        0        0          14944
29                598       0        0        0          17576
..                ...     ...      ...      ...            ...
536              1545       0        0        0         536089
537              2126       1        0        0         587590
538              2351       0        0        0         519347
539              1861       0        0        0         628251
540              1581       0        0        0         563642
541              2085       0        0        0         560763
542              1942       0        0        0         653407
543              2383       1        0        0        1088233
544              2467       1        0        0         566403
545              1845       0        0        0         675721
546              2228       0        0        0         572897
547              2993       1        0        0         782065
548              2167       1        0        0         622378
549              3055       1        0        0         786762
550              2377       0        0        0         896217
551              2889       1        0        0         763624
552              1674       0        0        0         760172
553              2373       1        0        0         971976
554              1805       0        0        0         831671
555              1899       1        0        0         844547
556              2523       1        0        0         984932
557              3436       1        0        0         957304
558              2594       1        0        0         926955
559              3498       1        0        0        1275470
560              3673       1        0        0        1203236
561              3988       1        0        0        1552150
562              2999       0        0        0        1436582
563              2686       0        0        1        1006364
564              3184       1        0        0        2101324
565              2361       1        0        0        1410271

[566 rows x 5 columns]

In [46]:
model = sm.OLS(y_train, new_x_train)
new_result = model.fit()
new1 = new_result.predict(new_x_test)
new1

0    1.053052e+06
1    1.171952e+06
2    7.178864e+04
3    7.306049e+04
4    1.581864e+05
dtype: float64

# 다중공선성

https://datascienceschool.net/view-notebook/36176e580d124612a376cf29872cd2f0/

# 잔차분석

https://datascienceschool.net/view-notebook/3ea68ac37aa846e58a8c330aad0bdbd1/